# Generated by Django 5.0.4 on 2024-04-26 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waitressPage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadComing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Шеф', 'Шеф'), ('Пекар', 'Пекар')], default='first_meal', max_length=255, verbose_name='Человек которые принес')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Количества')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bread_coming', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лепешка',
                'verbose_name_plural': 'Лепешки',
            },
        ),
        migrations.CreateModel(
            name='WaitressBread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Количества')),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bread_waitress', to='waitressPage.waitress')),
                ('waitress_bread_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bread_waitress_type', to='waitressPage.waitress')),
            ],
            options={
                'verbose_name': 'Лепешка официанта',
                'verbose_name_plural': 'Лепешки официанты',
            },
        ),
    ]
