# Define permissions for different roles
ROLE_PERMISSIONS = {
    "chef": ["can_access_report_notebook", "can_access_close_shift_waitress", ],
    "administrator": ["can_access_all"],
    "waitress": ["can_access_waitress_page"],
    # Add more roles and permissions as needed
}

# Define specific views permissions
VIEW_PERMISSIONS = {
    # CHEF PERMISSIONS
    "ReportNoteBook": ["chef"],
    "RobotView": ["chef"],
    "HistoryReportView": ["chef"],
    "HistoryDetailReportView": ["chef"],
    "RequestToCloseShiftWaitress": ["chef"],
    "RequestShiftDetailView": ["chef"],
    "EndRequestShiftDetailView": ["chef"],
    "DebtsWaitressByMonth": ["chef"],
    "DebtsByMonthDetailView": ["chef"],
    "DebtPaidByMonth": ["chef"],
    "SettingsProgramView": ["chef"],
    "InComeView": ["chef"],
    "WaitressPriceOfServiceMonthlyView": ["chef"],
    # WAITRESS
    "BreadPage": ["chef", "waitress", "administrator", ],
    "EditBreadMainPageView": ["chef", "waitress"],
    "DeleteBreadMainPageView": ["chef", "waitress"],
    "EditBreadComingView": ["chef", "waitress"],
    "WaitressBreadDeleteView": ["chef", "waitress"],
    "StartShiftWaitress": ["chef", "administrator", "employee", "waitress"],
    "StartLateUserShiftWaitress": ["employee", "waitress"],
    "WaitressPageView": ["waitress"],
    "PayWithQr": ["waitress", "chef"],
    "QrCodeInput": ["waitress", "chef"],
    "DesksSimpleView": ["waitress"],
    "DesksView": ["waitress"],
    "NewOrderView": ["waitress"],
    "EditOrderWaitress": ["waitress"],
    "KitchenWaitressView": ["waitress"],
    "AllWaitressView": ["waitress"],
    "BillWaitressView": ["waitress"],
    "BillWaitressDetailView": ["waitress"],
    "EndOrder": ["waitress"],
    "TakeAwayFoodView": ["waitress"],
    "NewOrderTakeAwayFood": ["waitress"],
    "BillTakeAwayFoodView": ["waitress"],
    "ListOfItemsWaitressView": ["waitress"],
    "BalanceFromCardView": ["waitress"],
    "EditOrderWaitressTakeAwayView": ["waitress"],
    "ConsumptionsWaitressHistoryView": ["waitress", "chef"],
    "ConsumptionsWaitressView": ["waitress"],
    "EndShiftWaitress": ["waitress"],
    "ProfilePageView": ["waitress", "chef", "administrator", "employee"],

    # CHEF ADMINISTRATOR
    "HomePageView": ["chef", "administrator", "employee", "samsishnik", "chebureki_maker", "cake_maker", "kassa"],
    "SettingsListView": ["chef", "administrator"],
    "OrderDrinksView": ["chef", "kassa"],
    "AverageQuantityMeals": ["chef", "administrator"],
    "ShiftAnalyticsView": ["chef"],
    "SamsaRestReportView": ["chef", "administrator"],
    "SamsaRestReportDetailView": ["chef", ],
    "AnalyticsReportView": ["chef", ],
    "WantToStartShift": ["chef", "administrator", "employee"],
    "ConfirmShiftStart": ["chef", "administrator", "employee"],
    "OrdersInKitchenView": ["chef", "administrator", "employee"],
    "UyghurKitchenView": ["chef", "administrator", "employee"],
    "NationalKitchenView": ["chef", "administrator", "employee"],
    "ControlKitchenOrders": ["chef", "administrator", "employee", "cake_maker"],
    "DeleteOrderView": ["chef", "administrator", "employee", "samsishnik"],
    "ControlDeletedOrderView": ["chef", "administrator"],
    "HistoryBillIsPaidView": ["chef", "administrator"],
    "RecoveryDeletedMealView": ["chef", "administrator", "employee"],
    "OrdersTea": ["chef", "administrator", "employee"],
    "ListOfNominationOrderView": ["chef", "administrator", "employee"],
    "MealListView": ["chef", "administrator", "employee"],
    "MealSearchView": ["chef", "administrator", "employee"],
    "AddMealView": ["chef", "administrator"],
    "EditMealsView": ["chef", "administrator"],
    "CommentsInMealView": ["chef", "administrator"],
    "EditCommentsMealsInMenu": ["chef", "administrator"],
    "StopListView": ["chef", "administrator", "employee"],
    "GroupStopListView": ["chef", "administrator", "employee"],
    "AddGroupNameToStopListView": ["chef", "administrator", "employee"],
    "AddGroupItemToStopListView": ["chef", "administrator", "employee"],
    "MenuView": ["chef", "administrator", "employee", "waitress"],
    "QuantityOfMealADay": ["chef", "administrator", "samsishnik"],
    "RatingMealView": ["chef", "administrator"],
    "MealInStockView": ["chef", "administrator", "employee"],
    "MeatOrderPageView": ["chef", "administrator", "employee"],
    "EditOrderMeatView": ["chef", "administrator", "employee"],
    "ProductListView": ["chef", "administrator", "employee"],
    "BillsAllKitchen": ["chef", "administrator", "employee"],
    "ReportYesterdayView": ["chef"],
    "HistoryQuantityOfMealsView": ["chef", "administrator"],
    "IngredientView": ["chef", "administrator"],
    "MealIngredientView": ["chef", "administrator"],
    "ProductPurchaseView": ["chef", "administrator"],
    "IngredientStockView": ["chef", "administrator"],

    # SAMSA KEBAB
    "OrdersSamsaKebabView": ["chef", "administrator", "employee", "samsishnik"],
    "OrdersSamsaView": ["chef", "administrator", "employee", "samsishnik"],
    "OrdersKebabView": ["chef", "administrator", "employee", "samsishnik"],
    "ControlSamsaKebabOrders": ["chef", "administrator", "samsishnik"],
    "SamsaReportAddView": ["chef", "administrator", "samsishnik"],
    "SamsaSettingsView": ["chef", "administrator", "samsishnik"],
    "EditSamsaConsumption": ["chef", "administrator", "samsishnik"],


    "ButcherMainView": ["chef", "butcher"],
    "ButcherMeatOrdersView": ["chef", "butcher"],
    "HistoryButcherMeatOrdersView": ["chef", "butcher"],
    "UnPaidMeatOrdersView": ["chef", "butcher"],

    # CHEF
    "SaleDayView": ["chef"],
    "SaleMonthView": ["chef"],
    "MealReportList": ["chef"],
    "ProductPriceView": ["chef"],
    "MealRecipesView": ["chef"],
    "NotEndedReportView": ["chef"],
    "ReportByHourView": ["chef"],
    "WaitressControlCrudReport": ["chef"],

    # Cakes
    "OrderCakesView": ["chef", "cake_maker"],
    "QuantityOfCakesView": ["chef", "cake_maker"],
    "ReportCakesView": ["chef", "cake_maker"],

    # Add more views and the allowed roles for each
}
