# Generated by Django 5.0.4 on 2024-09-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingskitchen',
            options={'verbose_name': 'Настройка кухни', 'verbose_name_plural': 'Настройка кухня'},
        ),
    ]
