# Generated by Django 5.0.4 on 2025-05-20 18:09

import apps.rayhan.homePage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=252, null=True, unique=True, verbose_name='Имя')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cooks', verbose_name='Фото')),
                ('work_start', models.TimeField(default=apps.rayhan.homePage.models.get_now, verbose_name='Время работы от')),
                ('work_end', models.TimeField(default=apps.rayhan.homePage.models.get_now, verbose_name='Время работы до')),
            ],
            options={
                'verbose_name': 'Наёмник',
                'verbose_name_plural': 'Наёмники',
            },
        ),
    ]
