# Generated by Django 5.0.4 on 2025-08-29 21:05

import apps.rayhan.homePage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Наёмник', 'verbose_name_plural': 'Наёмники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=252, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_end',
            field=models.TimeField(default=apps.rayhan.homePage.models.get_now, verbose_name='Время работы до'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_start',
            field=models.TimeField(default=apps.rayhan.homePage.models.get_now, verbose_name='Время работы от'),
        ),
    ]
