# Generated by Django 5.0.4 on 2025-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_alter_employee_options_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=252, null=True, unique=True, verbose_name='Имя'),
        ),
    ]
