# Generated by Django 5.0.4 on 2024-12-18 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamsaMeatRest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('samsa_meat_used_to', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Мясной самса')),
                ('samsa_potato_used_to', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Картошка самса')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='вес')),
                ('create_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Самса остатка',
                'verbose_name_plural': 'Самса остатки',
            },
        ),
        migrations.CreateModel(
            name='Samsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samsa_meat', models.PositiveIntegerField(verbose_name='Мясная самса')),
                ('samsa_potato', models.PositiveIntegerField(verbose_name='Самса картофельная')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата')),
                ('create_date', models.DateField(unique=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samsa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Самса',
                'verbose_name_plural': 'Самсы',
            },
        ),
        migrations.CreateModel(
            name='SamsaConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('quantity', models.CharField(max_length=100, verbose_name='Количества')),
                ('type_samsa', models.CharField(choices=[('картошка', 'картошка'), ('мясная', 'мясная')], default='картошка', max_length=255, verbose_name='Тип')),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samsa_consumption', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Самса расход',
                'verbose_name_plural': 'Самса расходы',
            },
        ),
        migrations.CreateModel(
            name='SamsaPriceDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samsa_meat_price', models.CharField(max_length=100, verbose_name='Мясная самса')),
                ('samsa_potato_price', models.CharField(max_length=100, verbose_name='Самса картофельная')),
                ('samsishnik_meat_pay', models.CharField(max_length=100, verbose_name='Зарплата шт мясная самса')),
                ('samsishnik_potato_pay', models.CharField(max_length=100, verbose_name='Зарплата шт картофельная самса')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samsa_price', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Самса цена зарплата',
                'verbose_name_plural': 'Самсы цены зарплаты',
            },
        ),
    ]
