# Generated by Django 5.0.4 on 2025-05-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsa_kebab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samsa',
            name='samsa_potato',
        ),
        migrations.AddField(
            model_name='samsa',
            name='samsa_little',
            field=models.PositiveIntegerField(default=0, verbose_name='Тамчы самса'),
        ),
        migrations.AlterField(
            model_name='samsa',
            name='samsa_meat',
            field=models.PositiveIntegerField(default=0, verbose_name='Обычный самса'),
        ),
    ]
