# Generated by Django 5.0.4 on 2025-05-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsa_kebab', '0002_remove_samsa_samsa_potato_samsa_samsa_little_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsa',
            name='for_another_cafe',
            field=models.PositiveIntegerField(default=0, verbose_name='для Райхан кафе'),
        ),
        migrations.AddField(
            model_name='samsa',
            name='take_away_summa',
            field=models.PositiveIntegerField(default=0, verbose_name='С собой деньги'),
        ),
    ]
