# Generated by Django 5.0.4 on 2025-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsa_kebab', '0003_samsa_for_another_cafe_samsa_take_away_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samsaconsumption',
            name='type_samsa',
            field=models.CharField(choices=[('тамчы', 'тамчы'), ('мясная', 'мясная')], default='тамчы', max_length=255, verbose_name='Тип'),
        ),
    ]
