# Generated by Django 5.0.4 on 2025-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsa_kebab', '0004_alter_samsaconsumption_type_samsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samsapricedefault',
            name='samsa_potato_price',
        ),
        migrations.AddField(
            model_name='samsapricedefault',
            name='samsa_tamchi_price',
            field=models.CharField(default='0', max_length=100, verbose_name='Самса тамчы'),
        ),
    ]
