# Generated by Django 5.0.4 on 2025-06-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsa_kebab', '0005_remove_samsapricedefault_samsa_potato_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsa',
            name='remainder_samsa_little',
            field=models.PositiveIntegerField(default=0, verbose_name='Тамчы самса'),
        ),
        migrations.AddField(
            model_name='samsa',
            name='remainder_samsa_meat',
            field=models.PositiveIntegerField(default=0, verbose_name='Обычный самса'),
        ),
    ]
