# Generated by Django 5.0.4 on 2025-06-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsa_kebab', '0006_samsa_remainder_samsa_little_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samsa',
            name='remainder_samsa_little',
            field=models.PositiveIntegerField(default=0, verbose_name='Остатка тамчы самсы'),
        ),
        migrations.AlterField(
            model_name='samsa',
            name='remainder_samsa_meat',
            field=models.PositiveIntegerField(default=0, verbose_name='Остатка большое самсы'),
        ),
    ]
