# Generated by Django 5.0.4 on 2024-04-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип контейнера')),
            ],
            options={
                'verbose_name': 'Тип контейнера',
                'verbose_name_plural': 'Типы контейнеров',
            },
        ),
        migrations.CreateModel(
            name='GroupByOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Группа для официантов')),
            ],
            options={
                'verbose_name': 'Группа для официантов',
                'verbose_name_plural': 'Группы для официантов',
            },
        ),
        migrations.CreateModel(
            name='GroupNameStopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Наименование группа')),
                ('create_date', models.DateField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Наименование групп стоп лист',
                'verbose_name_plural': 'Наименование групп стоп лист',
            },
        ),
        migrations.CreateModel(
            name='MealGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа блюд',
                'verbose_name_plural': 'Группы блюд',
            },
        ),
        migrations.CreateModel(
            name='MealsInMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя блюда')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_of_a_person', models.PositiveIntegerField(default=0, verbose_name='Количество для одного человека')),
                ('filter_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealList.groupbyother', verbose_name='Группа для официантов')),
                ('group_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealList.mealgroup', verbose_name='Группа')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealList.containertype', verbose_name='Тип контейнера')),
            ],
            options={
                'verbose_name': 'Меню блюда',
                'verbose_name_plural': 'Меню блюды',
                'ordering': ['-group_item'],
            },
        ),
        migrations.CreateModel(
            name='InStockInMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='0', verbose_name='Количества')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('name_related_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instock_meal', to='mealList.mealsinmenu', verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Блюда которые осталось штук',
                'verbose_name_plural': 'Блюды которые осталось штук',
                'ordering': ['-name_related_meal'],
            },
        ),
        migrations.CreateModel(
            name='GroupItemStopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='Дата добавления')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_item_stop_list', to='mealList.groupnamestoplist', verbose_name='Группа блюда')),
                ('name_related_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals_to_stop_list', to='mealList.mealsinmenu', verbose_name='Имя блюда')),
            ],
            options={
                'verbose_name': 'Группировка стоп лист',
                'verbose_name_plural': 'Группировка стоп листы',
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_related_meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='mealList.mealsinmenu', verbose_name='Тип напиток')),
            ],
            options={
                'verbose_name': 'Напитка',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='CommentsInMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя коммента')),
                ('is_active', models.BooleanField(default=True)),
                ('name_related_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mealList.mealsinmenu', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Коментария блюда',
                'verbose_name_plural': 'Коментарии блюды',
                'ordering': ['-name_related_meal'],
            },
        ),
        migrations.CreateModel(
            name='BlackListToKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_related_meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='black_list_to_kitchen', to='mealList.mealsinmenu', verbose_name='Тип блюд')),
            ],
            options={
                'verbose_name': 'Чёрный список для кухни',
                'verbose_name_plural': 'Чёрный списки для кухни',
            },
        ),
        migrations.CreateModel(
            name='MealsToShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='mealList.mealsinmenu', verbose_name='Блюдо в меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='RatingMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='0', verbose_name='Количества')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True)),
                ('name_related_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_meal', to='mealList.mealsinmenu', verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Рейтинговая блюд',
                'verbose_name_plural': 'Рейтинговая блюда',
                'ordering': ['-name_related_meal'],
            },
        ),
        migrations.CreateModel(
            name='StopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stopped', models.BooleanField(default=False)),
                ('create_date', models.DateField(verbose_name='Дата добавления')),
                ('time_create_date', models.DateTimeField(null=True, verbose_name='Время стоп заказа')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_list', to='mealList.mealsinmenu', verbose_name='Имя блюд')),
            ],
            options={
                'verbose_name': 'Стоп лист',
                'verbose_name_plural': 'Стоп листы',
            },
        ),
    ]
