# Generated by Django 5.0.4 on 2024-10-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0002_alter_commentsinmeal_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя продукта')),
                ('price', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Цена')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления')),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата изменения')),
            ],
        ),
    ]
