# Generated by Django 5.0.4 on 2024-10-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0003_productprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprices',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Цена'),
        ),
    ]
