# Generated by Django 5.0.4 on 2024-10-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0004_alter_productprices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='type',
            field=models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт'), ('l', 'литр')], default='kg', max_length=3, verbose_name='Тип'),
        ),
    ]
