# Generated by Django 5.0.4 on 2024-10-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0005_productprices_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealstoshow',
            name='type_distribution',
            field=models.CharField(blank=True, choices=[('complect_meal', 'Комплект блюд'), ('by_one_meal', 'Порционное блюдо')], max_length=50, null=True, verbose_name='Тип распределения'),
        ),
        migrations.CreateModel(
            name='MealRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Вес')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_recipes', to='mealList.mealstoshow', verbose_name='Осново блюдо')),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_meal_products', to='mealList.mealstoshow', verbose_name='продукты')),
            ],
        ),
    ]
