# Generated by Django 5.0.4 on 2024-10-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0006_mealstoshow_type_distribution_mealrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecipes',
            name='name_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_meal_products', to='mealList.productprices', verbose_name='продукты'),
        ),
    ]
