# Generated by Django 5.0.4 on 2024-10-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0007_alter_mealrecipes_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecipes',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес'),
        ),
    ]
