# Generated by Django 5.0.4 on 2024-10-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0008_alter_mealrecipes_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealstoshow',
            name='from_one_meal',
            field=models.IntegerField(blank=True, null=True, verbose_name='блюда из одного штука'),
        ),
    ]
