# Generated by Django 5.0.4 on 2024-11-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0009_mealstoshow_from_one_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecipes',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес'),
        ),
    ]
