# Generated by Django 5.0.4 on 2024-11-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0010_alter_mealrecipes_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecipes',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес'),
        ),
    ]
