# Generated by Django 5.0.4 on 2024-12-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0011_alter_mealrecipes_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealrecipes',
            options={'verbose_name': 'Рецепты блюд', 'verbose_name_plural': 'Рецепты блюда'},
        ),
        migrations.AlterModelOptions(
            name='productprices',
            options={'verbose_name': 'Цены продукты', 'verbose_name_plural': 'Цены продуктов'},
        ),
    ]
