# Generated by Django 5.0.4 on 2025-02-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0012_alter_mealrecipes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UyghurMealsToKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_related_meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uyghur_meals_to_kitchen', to='mealList.mealsinmenu', verbose_name='Тип блюд')),
            ],
            options={
                'verbose_name': 'Уйгурская кухня',
                'verbose_name_plural': 'Уйгурская кухня',
            },
        ),
    ]
