# Generated by Django 5.0.4 on 2025-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0013_uyghurmealstokitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealstoshow',
            name='consumption',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Расход'),
        ),
    ]
