# Generated by Django 5.0.4 on 2025-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0014_mealstoshow_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='type_products',
            field=models.CharField(choices=[('bazaar', 'базар'), ('product', 'продукты'), ('shop', 'магазин')], default='product', max_length=250, verbose_name='Группа продукты'),
        ),
    ]
