# Generated by Django 5.0.4 on 2025-04-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0015_productprices_type_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='is_added_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
