# Generated by Django 5.0.4 on 2025-05-09 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0017_mealstoshow_this_meal_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealstoshow',
            name='this_meal_consumption',
        ),
        migrations.AddField(
            model_name='productprices',
            name='this_meal_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_meals', to='mealList.mealstoshow', verbose_name='Блюдо-основа'),
        ),
    ]
