# Generated by Django 5.0.4 on 2025-08-07 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0019_dish_ingredient_dishvariant_dishpreparation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.RemoveField(
            model_name='dishvariant',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishingredient',
            name='dish_variant',
        ),
        migrations.RemoveField(
            model_name='dishingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='dishpreparation',
            name='dish_variant',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='ingredient',
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущая цена'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='source',
            field=models.CharField(choices=[('bazaar', 'Базар'), ('market', 'Магазин'), ('warehouse', 'Склад')], default='market', max_length=50, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('pcs', 'шт'), ('l', 'литр')], default='kg', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealList.ingredient', verbose_name='Ингредиент')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='mealList.meal', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Ингредиент в блюде',
                'verbose_name_plural': 'Ингредиенты в блюде',
                'unique_together': {('meal', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='MealPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество приготовлено')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата приготовления')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='mealList.meal', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Приготовление блюда',
                'verbose_name_plural': 'Приготовления блюд',
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='mealList.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Покупка ингредиента',
                'verbose_name_plural': 'Покупки ингредиентов',
            },
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='DishIngredient',
        ),
        migrations.DeleteModel(
            name='DishPreparation',
        ),
        migrations.DeleteModel(
            name='DishVariant',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
