# Generated by Django 5.0.4 on 2025-08-07 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0020_expense_income_meal_remove_dishvariant_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealpreparation',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='mealList.mealsinmenu', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='mealList.mealsinmenu', verbose_name='Блюдо'),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
