# Generated by Django 5.0.4 on 2025-08-07 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0021_alter_mealpreparation_meal_alter_mealingredient_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество использовано')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата использования')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used', to='mealList.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Ингредиент использовано',
                'verbose_name_plural': 'Ингредиенты использованы',
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
