# Generated by Django 5.0.4 on 2025-08-07 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0022_usedingredient_delete_expense_delete_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialIngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальный остаток')),
                ('date', models.DateField(verbose_name='Дата (начало месяца)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealList.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Начальный остаток',
                'verbose_name_plural': 'Начальные остатки',
                'unique_together': {('ingredient', 'date')},
            },
        ),
    ]
