# Generated by Django 5.0.4 on 2025-08-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0023_initialingredientstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedingredient',
            options={'verbose_name': 'Ингредиент использован', 'verbose_name_plural': 'Ингредиенты использованы'},
        ),
        migrations.AddField(
            model_name='usedingredient',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_used', to='mealList.mealstoshow', verbose_name='Блюдо'),
        ),
    ]
