# Generated by Django 5.0.4 on 2025-08-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealList', '0024_alter_usedingredient_options_usedingredient_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedingredient',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_used', to='mealList.mealsinmenu', verbose_name='Блюдо'),
        ),
    ]
