# Generated by Django 5.0.4 on 2024-09-14 19:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waitressPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_group', models.PositiveSmallIntegerField(verbose_name='Группа столов')),
                ('desks', models.CharField(max_length=255, verbose_name='Номера столов')),
                ('shift_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата смены')),
                ('waitress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_assignments', to='waitressPage.waitress')),
            ],
            options={
                'verbose_name': 'Назначение столов',
                'verbose_name_plural': 'Назначения столов',
                'ordering': ['shift_date', 'desk_group'],
                'unique_together': {('waitress', 'shift_date', 'desk_group')},
            },
        ),
    ]
