# Generated by Django 5.0.4 on 2024-09-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveSmallIntegerField(verbose_name='Номер группы')),
                ('desks', models.CharField(max_length=255, verbose_name='Номера столов')),
            ],
            options={
                'verbose_name': 'Группа столов',
                'verbose_name_plural': 'Группы столов',
                'ordering': ['group_number'],
            },
        ),
        migrations.DeleteModel(
            name='DeskAssignment',
        ),
    ]
