# Generated by Django 5.0.4 on 2024-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_deskgroup_delete_deskassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskgroup',
            name='desks',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номера столов'),
        ),
    ]
