# Generated by Django 5.0.4 on 2024-09-15 16:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_deskgroup_desks'),
        ('waitressPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата смены')),
                ('desk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.deskgroup', verbose_name='Группа столов')),
                ('waitress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_assignments', to='waitressPage.waitress')),
            ],
            options={
                'verbose_name': 'Назначение столов',
                'verbose_name_plural': 'Назначения столов',
                'ordering': ['shift_date', 'desk_group'],
            },
        ),
        migrations.AddConstraint(
            model_name='deskassignment',
            constraint=models.UniqueConstraint(fields=('waitress', 'shift_date', 'desk_group'), name='unique_assignment'),
        ),
    ]
