# Generated by Django 5.0.4 on 2024-09-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_deskassignment_deskassignment_unique_assignment'),
        ('waitressPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deskassignment',
            name='waitress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_assignments', to='waitressPage.waitress', verbose_name='Официантка'),
        ),
        migrations.AlterField(
            model_name='deskgroup',
            name='group_number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер группы'),
        ),
    ]
