# Generated by Django 5.0.4 on 2024-10-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_deskassignment_waitress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveEveryDaysReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_balance', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('kitchen', models.PositiveIntegerField(default=0, verbose_name='Кухня')),
                ('samsa', models.PositiveIntegerField(default=0, verbose_name='Самса')),
                ('kebab', models.PositiveIntegerField(default=0, verbose_name='Шашлыки')),
                ('create_date', models.DateTimeField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Сохранение отчета',
                'verbose_name_plural': 'Сохранение отчеты',
            },
        ),
    ]
