# Generated by Django 5.0.4 on 2024-12-19 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_saveeverydaysreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количества')),
                ('create_date', models.DateTimeField(verbose_name='Дата')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блюд штук',
                'verbose_name_plural': 'Блюды штук',
            },
        ),
    ]
