# Generated by Django 5.2.8 on 2026-01-06 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_countmeals'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('made_pirojki', models.PositiveIntegerField(default=0, verbose_name='Пирожки сделано')),
                ('made_belyash', models.PositiveIntegerField(default=0, verbose_name='Беляши сделано')),
                ('made_cheburek', models.PositiveIntegerField(default=0, verbose_name='Чебуреки сделано')),
                ('left_pirojki', models.PositiveIntegerField(default=0, verbose_name='Пирожки остаток')),
                ('left_belyash', models.PositiveIntegerField(default=0, verbose_name='Беляши остаток')),
                ('left_cheburek', models.PositiveIntegerField(default=0, verbose_name='Чебуреки остаток')),
                ('cash_som', models.PositiveIntegerField(default=0, verbose_name='Наличные (сом)')),
                ('mbank', models.PositiveIntegerField(default=0, verbose_name='МБанк')),
                ('cafe_sales', models.PositiveIntegerField(default=0, verbose_name='Продажи в кафе')),
                ('cakes_waitress_sum', models.PositiveIntegerField(default=0, verbose_name='Десерты официантов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
