# Generated by Django 5.2.8 on 2026-01-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_bakerydailyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerydailyreport',
            name='date',
        ),
    ]
