# Generated by Django 5.2.8 on 2026-01-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_remove_bakerydailyreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerydailyreport',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата отчёта'),
        ),
    ]
