# Generated by Django 5.2.8 on 2026-01-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_bakerydailyreport_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerydailyreport',
            name='cafe_sales',
        ),
    ]
