# Generated by Django 5.0.4 on 2024-04-26 19:17

import apps.account.models
import django.core.validators
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activate_code', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('roles', models.CharField(choices=[('chef', 'шеф'), ('administrator', 'Администратор'), ('employee', 'Работник'), ('samsishnik', 'Cамсышник'), ('waitress', 'Официант'), ('butcher', 'Мясник'), ('demo', 'Демо'), ('customer', 'Клиент')], default='employee', max_length=255, verbose_name='Тип')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('rate', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_rate_active', models.BooleanField(default=False)),
                ('balance_of_user', models.PositiveIntegerField(default=0, verbose_name='баланс')),
                ('theme_order', models.CharField(blank=True, default='unusual_bg_blue', max_length=250, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Фото')),
                ('trophies', models.IntegerField(default=0, verbose_name='Трофеи')),
                ('type_rating', models.IntegerField(choices=[(1, 'Базовый'), (2, 'Бронзовый'), (3, 'Серебряный'), (4, 'Золотой'), (5, 'Премиум'), (6, 'Элитный'), (7, 'Профессиональный')], default=1, verbose_name='Наименование рейтинга')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.account.models.CustomUserManager()),
            ],
        ),
    ]
