# Generated by Django 5.0.4 on 2024-10-17 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountsinstagramphishing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsinstagramphishing',
            options={'verbose_name': 'Инстаграмм', 'verbose_name_plural': 'Инстаграмм аккаунты'},
        ),
    ]
