# Generated by Django 5.0.4 on 2024-12-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
