# Generated by Django 5.0.4 on 2024-12-22 08:36

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pushnotificationtosubscribeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotificationtosubscribeduser',
            name='roles_user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='trophies',
            field=models.IntegerField(default=0, validators=[apps.account.models.CustomUser.validate_positive], verbose_name='Трофеи'),
        ),
    ]
