# Generated by Django 5.0.4 on 2025-01-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_rate_usertrophystat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertrophystat',
            options={'verbose_name': 'Трофеи', 'verbose_name_plural': 'Трофеи'},
        ),
    ]
