# Generated by Django 5.0.4 on 2025-02-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_usertrophystat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('chef', 'шеф'), ('administrator', 'Администратор'), ('employee', 'Работник'), ('samsishnik', 'Cамсышник'), ('cake_maker', 'Тортышник'), ('chebureki_maker', 'Чебурешник'), ('waitress', 'Официант'), ('butcher', 'Мясник'), ('demo', 'Демо'), ('customer', 'Клиент')], default='employee', max_length=255, verbose_name='Тип'),
        ),
    ]
