# Generated by Django 5.2.8 on 2026-03-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('chef', 'шеф'), ('administrator', 'Администратор'), ('employee', 'Работник'), ('samsishnik', 'Cамсышник'), ('cake_maker', 'Тортышник'), ('chebureki_maker', 'Чебурешник'), ('kassa', 'Кассир'), ('waitress', 'Официант'), ('butcher', 'Мясник'), ('demo', 'Демо'), ('customer', 'Клиент')], default='employee', max_length=255, verbose_name='Тип'),
        ),
    ]
