# Generated by Django 5.0.4 on 2024-09-23 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatSettingsDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Имя блюда')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='вес')),
            ],
            options={
                'verbose_name': 'Мясо по умолчанию',
                'verbose_name_plural': 'Мясы по умолчанию',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='MeatOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='вес')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('create_time_date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('is_watched', models.BooleanField(default=False)),
                ('watched_time', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мясо заказ',
                'verbose_name_plural': 'Мясо заказы',
                'ordering': ['-name'],
            },
        ),
    ]
