# Generated by Django 5.0.4 on 2024-09-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meatorder',
            unique_together={('name', 'create_date')},
        ),
    ]
