# Generated by Django 5.0.4 on 2024-09-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0002_alter_meatorder_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meatorder',
            name='create_date',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
    ]
