# Generated by Django 5.0.4 on 2024-11-17 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0003_alter_meatorder_create_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('price', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='цена')),
                ('create_date', models.DateField(verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_price', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
