# Generated by Django 5.0.4 on 2024-11-17 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0004_meatprices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatOrdersForButcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес')),
                ('summa', models.IntegerField(verbose_name='Сумма')),
                ('create_date', models.DateField(verbose_name='Дата добавления')),
                ('is_paid', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_for_butcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
