# Generated by Django 5.0.4 on 2024-12-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0005_meatordersforbutcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meatordersforbutcher',
            options={'verbose_name': 'Мясо мясника', 'verbose_name_plural': 'Мясы мясника'},
        ),
    ]
