# Generated by Django 5.0.4 on 2024-12-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meat', '0006_alter_meatordersforbutcher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meatprices',
            options={'ordering': ['-name'], 'verbose_name': 'Мясо цена', 'verbose_name_plural': 'Мясо цены'},
        ),
    ]
