# Generated by Django 5.0.4 on 2025-02-11 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя продукта')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Количества')),
                ('type', models.CharField(choices=[('кг', 'кг'), ('гр', 'гр'), ('шт', 'шт')], default='кг', max_length=255, verbose_name='Тип')),
                ('group_item', models.CharField(choices=[('product', 'Продукты'), ('bazaar', 'Базар'), ('shop', 'Магазин')], default='product', max_length=255, verbose_name='Группа')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_added_to_cart', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продукта',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('create_date', models.DateField()),
                ('group_item', models.CharField(choices=[('product', 'Продукты'), ('bazaar', 'Базар'), ('shop', 'Магазин')], default='product', max_length=255, verbose_name='Группа')),
                ('is_paid', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history', to='products.product')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'Истории заказа',
                'ordering': ['-group_item'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(default=1)),
                ('group_item', models.CharField(choices=[('product', 'Продукты'), ('bazaar', 'Базар'), ('shop', 'Магазин')], default='product', max_length=255, verbose_name='Группа')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_in_cart', to='products.product')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
