# Generated by Django 5.0.4 on 2024-04-26 19:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('number', models.PositiveIntegerField(default='0', verbose_name='Количества')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='DeletedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя блюда заказа')),
                ('number_of_desk', models.PositiveIntegerField(default='0', verbose_name='Номер стола')),
                ('people_in_desk', models.PositiveIntegerField(default='0', verbose_name='Количества людей')),
                ('price_of_service', models.PositiveIntegerField(default='0', verbose_name='Услуга')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Количества')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('create_date', models.DateTimeField(verbose_name='Дата добавления')),
                ('is_paid', models.BooleanField(default=False)),
                ('order_done', models.BooleanField(default=False)),
                ('order_is_edited', models.BooleanField(default=False)),
                ('takeaway_food', models.BooleanField(default=False)),
                ('order_closed_time', models.DateTimeField(null=True, verbose_name='Время завершения заказа')),
                ('time_cooked', models.IntegerField(blank=True, null=True, verbose_name='Время приготовления')),
                ('number_of_order', models.PositiveIntegerField(default='0', verbose_name='Номер заказа')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Коментарии блюд')),
                ('waiting_takeaway_food', models.BooleanField(default=False)),
                ('person_in_desk_order', models.BooleanField(default=False)),
                ('code_bill', models.PositiveIntegerField()),
                ('reason_to_deleting', models.TextField(blank=True, null=True, verbose_name='Причина удаления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleting_meal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Удаленный заказ',
                'verbose_name_plural': 'Удаленный заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя блюда заказа')),
                ('number_of_desk', models.PositiveIntegerField(default='0', verbose_name='Номер стола')),
                ('people_in_desk', models.PositiveIntegerField(default='0', verbose_name='Количества людей')),
                ('price_of_service', models.PositiveIntegerField(default='0', verbose_name='Услуга')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Количества')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('create_date', models.DateTimeField(verbose_name='Дата добавления')),
                ('is_paid', models.BooleanField(default=False)),
                ('order_done', models.BooleanField(default=False)),
                ('order_is_edited', models.BooleanField(default=False)),
                ('takeaway_food', models.BooleanField(default=False)),
                ('order_closed_time', models.DateTimeField(null=True, verbose_name='Время завершения заказа')),
                ('time_cooked', models.IntegerField(blank=True, null=True, verbose_name='Время приготовления')),
                ('number_of_order', models.PositiveIntegerField(default='0', verbose_name='Номер заказа')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Коментарии блюд')),
                ('waiting_takeaway_food', models.BooleanField(default=False)),
                ('person_in_desk_order', models.BooleanField(default=False)),
                ('code_bill', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_meal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ блюда',
                'verbose_name_plural': 'Заказы блюд',
            },
        ),
        migrations.CreateModel(
            name='RatingControlWaitress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователья')),
                ('reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='Причина')),
                ('quantity', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата добавления')),
                ('type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitress_rating_control', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контроль рейтинга',
                'verbose_name_plural': 'Контроль рейтингов',
            },
        ),
        migrations.CreateModel(
            name='Waitress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.BooleanField(default=False)),
                ('time_started_shift', models.DateTimeField(verbose_name='Дата начала')),
                ('time_ended_shift', models.DateTimeField(blank=True, null=True, verbose_name='Дата конец')),
                ('balance', models.PositiveIntegerField(default='0', verbose_name='Сумма скопления официанта')),
                ('waiter_service', models.PositiveIntegerField(default='0', verbose_name='Услуга официанта')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата добавления')),
                ('consumption', models.PositiveIntegerField(default='0', verbose_name='Расход')),
                ('kitchen', models.PositiveIntegerField(default='0', verbose_name='Кухня')),
                ('samsa', models.PositiveIntegerField(default='0', verbose_name='Самса')),
                ('samsa_potato', models.PositiveIntegerField(default='0', verbose_name='Самса картошка')),
                ('kebab', models.PositiveIntegerField(default='0', verbose_name='Шашлык')),
                ('bread', models.PositiveIntegerField(default='0', verbose_name='Нан')),
                ('tea', models.PositiveIntegerField(default='0', verbose_name='Чай')),
                ('sherbet', models.PositiveIntegerField(default='0', verbose_name='Шербет')),
                ('drinks', models.PositiveIntegerField(default='0', verbose_name='Напитки')),
                ('wanted_to_close_shift', models.BooleanField(default=False)),
                ('wanted_to_start_shift', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('error_peoples', models.PositiveIntegerField(default='0', verbose_name='Количества людей которые не добавлен')),
                ('block_start_time', models.DateTimeField(blank=True, null=True)),
                ('takeaway_food', models.PositiveIntegerField(default='0', verbose_name='С сабой')),
                ('quantity_of_blocked', models.PositiveIntegerField(default='0', verbose_name='Количества блокировка')),
                ('deleted_meals', models.PositiveIntegerField(default='0', verbose_name='Количества удаленный заказы')),
                ('waitress_is_edited', models.BooleanField(default=False, verbose_name='Изменил самса шашлыки')),
                ('paid_with_card', models.PositiveIntegerField(default='0', verbose_name='Баланс с карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Официантка',
                'verbose_name_plural': 'Официантки',
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionWaitress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=252, null=True, verbose_name='Имя расхода')),
                ('summa', models.PositiveIntegerField(default='0', verbose_name='Сумма')),
                ('is_paid', models.BooleanField(default=False)),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_waitress', to='waitressPage.waitress')),
            ],
            options={
                'verbose_name': 'Расход официантка',
                'verbose_name_plural': 'Расход официантки',
                'ordering': ['-user'],
            },
        ),
    ]
