# Generated by Django 5.0.4 on 2024-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='order_samsa_kebab',
            field=models.BooleanField(default=False),
        ),
    ]
