# Generated by Django 5.0.4 on 2024-12-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0002_ordermeal_order_samsa_kebab'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedmeal',
            name='order_samsa_kebab',
            field=models.BooleanField(default=False),
        ),
    ]
