# Generated by Django 5.0.4 on 2024-12-30 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0003_deletedmeal_order_samsa_kebab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitressBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('waitress_service', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('number_of_desk', models.PositiveIntegerField(verbose_name='Номер стола')),
                ('number_of_order', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('create_date', models.DateTimeField(verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitress_bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
