# Generated by Django 5.0.4 on 2024-12-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0004_waitressbank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitressbank',
            options={'verbose_name': 'Банк официанта', 'verbose_name_plural': 'Банк официантов'},
        ),
        migrations.AlterField(
            model_name='waitressbank',
            name='waitress_service',
            field=models.PositiveIntegerField(default=0, verbose_name='Услуга'),
        ),
    ]
