# Generated by Django 5.0.4 on 2025-01-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0005_alter_waitressbank_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
