# Generated by Django 5.0.4 on 2025-02-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0006_ordermeal_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitress',
            name='cakes',
            field=models.PositiveIntegerField(default='0', verbose_name='Десерты'),
        ),
        migrations.AddField(
            model_name='waitress',
            name='сhebureki',
            field=models.PositiveIntegerField(default='0', verbose_name='Чебуреки'),
        ),
    ]
