# Generated by Django 5.0.4 on 2025-07-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0007_waitress_cakes_waitress_сhebureki'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='order_cakes',
            field=models.BooleanField(default=False),
        ),
    ]
