# Generated by Django 5.2.8 on 2026-04-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0008_ordermeal_order_cakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='order_kassa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermeal',
            name='tax_sent',
            field=models.BooleanField(default=False),
        ),
    ]
