# Generated by Django 5.2.8 on 2026-04-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitressPage', '0010_clientorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermeal',
            name='online_order',
            field=models.BooleanField(default=False),
        ),
    ]
